-- ============================================================
-- TRABAJO TERMINAL
-- Sistema de anotación del subconjunto enriquecido de MURA
-- Esquema inicial de base de datos
-- ============================================================


-- ============================================================
-- 1. ESPECIALISTAS
-- ============================================================

CREATE TABLE specialists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Usuario correspondiente en Supabase Auth.
    auth_user_id UUID UNIQUE,

    specialist_code VARCHAR(30) UNIQUE NOT NULL,
    access_code_hash TEXT,

    display_name VARCHAR(100),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT specialists_auth_user_fk
        FOREIGN KEY (auth_user_id)
        REFERENCES auth.users(id)
        ON DELETE SET NULL
);


-- ============================================================
-- 2. CASOS
-- Una fila por cada una de las 2,000 radiografías.
-- ============================================================

CREATE TABLE cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    annotation_case_id VARCHAR(30) UNIQUE NOT NULL,

    region VARCHAR(30) NOT NULL,

    -- Nombre que tendrá la imagen en Storage.
    image_filename VARCHAR(255) UNIQUE NOT NULL,

    -- Ruta interna dentro del bucket privado.
    storage_path TEXT UNIQUE NOT NULL,

    is_shared BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT cases_region_check CHECK (
        region IN (
            'XR_ELBOW',
            'XR_FINGER',
            'XR_FOREARM',
            'XR_HAND',
            'XR_HUMERUS',
            'XR_SHOULDER',
            'XR_WRIST'
        )
    )
);


-- ============================================================
-- 3. ASIGNACIONES
-- Relaciona cada caso con el especialista que debe evaluarlo.
--
-- Casos exclusivos:
--     1 asignación
--
-- Casos compartidos:
--     3 asignaciones
-- ============================================================

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    case_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,

    -- Orden independiente para presentar los casos.
    presentation_order INTEGER NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT assignments_case_fk
        FOREIGN KEY (case_id)
        REFERENCES cases(id)
        ON DELETE CASCADE,

    CONSTRAINT assignments_specialist_fk
        FOREIGN KEY (specialist_id)
        REFERENCES specialists(id)
        ON DELETE CASCADE,

    CONSTRAINT assignments_unique_case_specialist
        UNIQUE (case_id, specialist_id),

    CONSTRAINT assignments_unique_order
        UNIQUE (specialist_id, presentation_order),

    CONSTRAINT assignments_status_check CHECK (
        status IN (
            'PENDING',
            'IN_PROGRESS',
            'COMPLETED',
            'FLAGGED'
        )
    )
);


-- ============================================================
-- 4. ANOTACIONES
--
-- Una anotación por asignación.
-- La anotación pertenece a la combinación:
-- caso + especialista.
--
-- Los hallazgos utilizan tres estados:
-- PRESENT
-- ABSENT
-- INDETERMINATE
-- ============================================================

CREATE TABLE annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    assignment_id BIGINT UNIQUE NOT NULL,

    fracture_status VARCHAR(20),
    degenerative_status VARCHAR(20),
    hardware_status VARCHAR(20),
    other_status VARCHAR(20),

    -- Obligatorio a nivel de aplicación cuando
    -- other_status = PRESENT.
    other_description TEXT,

    -- Si la imagen no puede evaluarse clínicamente.
    not_evaluable BOOLEAN NOT NULL DEFAULT FALSE,

    -- Comentario opcional del especialista.
    comments TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT annotations_assignment_fk
        FOREIGN KEY (assignment_id)
        REFERENCES assignments(id)
        ON DELETE CASCADE,

    CONSTRAINT annotations_fracture_check CHECK (
        fracture_status IS NULL OR
        fracture_status IN ('PRESENT', 'ABSENT', 'INDETERMINATE')
    ),

    CONSTRAINT annotations_degenerative_check CHECK (
        degenerative_status IS NULL OR
        degenerative_status IN ('PRESENT', 'ABSENT', 'INDETERMINATE')
    ),

    CONSTRAINT annotations_hardware_check CHECK (
        hardware_status IS NULL OR
        hardware_status IN ('PRESENT', 'ABSENT', 'INDETERMINATE')
    ),

    CONSTRAINT annotations_other_check CHECK (
        other_status IS NULL OR
        other_status IN ('PRESENT', 'ABSENT', 'INDETERMINATE')
    ),

    CONSTRAINT annotations_other_description_check CHECK (
        other_status <> 'PRESENT'
        OR NULLIF(TRIM(other_description), '') IS NOT NULL
    )
);


-- ============================================================
-- 5. BOUNDING BOXES
--
-- Cada anotación puede tener cero, una o múltiples cajas.
--
-- Se almacenan coordenadas normalizadas [0,1].
-- Esto permite mostrar las cajas correctamente aunque la
-- imagen cambie de tamaño en el navegador.
-- ============================================================

CREATE TABLE bounding_boxes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    annotation_id BIGINT NOT NULL,

    finding_type VARCHAR(30) NOT NULL,

    bbox_index INTEGER NOT NULL,

    x_min DOUBLE PRECISION NOT NULL,
    y_min DOUBLE PRECISION NOT NULL,
    x_max DOUBLE PRECISION NOT NULL,
    y_max DOUBLE PRECISION NOT NULL,

    -- Dimensiones originales de la imagen utilizadas
    -- cuando se creó la caja.
    image_width INTEGER NOT NULL,
    image_height INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT bounding_boxes_annotation_fk
        FOREIGN KEY (annotation_id)
        REFERENCES annotations(id)
        ON DELETE CASCADE,

    CONSTRAINT bounding_boxes_finding_check CHECK (
        finding_type IN (
            'FRACTURE',
            'DEGENERATIVE',
            'HARDWARE',
            'OTHER'
        )
    ),

    CONSTRAINT bounding_boxes_index_unique
        UNIQUE (annotation_id, bbox_index),

    CONSTRAINT bounding_boxes_coordinates_check CHECK (
        x_min >= 0 AND
        y_min >= 0 AND
        x_max <= 1 AND
        y_max <= 1 AND
        x_min < x_max AND
        y_min < y_max
    ),

    CONSTRAINT bounding_boxes_dimensions_check CHECK (
        image_width > 0 AND
        image_height > 0
    )
);


-- ============================================================
-- 6. AUDITORÍA
--
-- Permitirá registrar acciones importantes realizadas
-- durante el proceso de anotación.
-- ============================================================

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    specialist_id BIGINT,
    assignment_id BIGINT,

    action VARCHAR(100) NOT NULL,

    details JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT audit_log_specialist_fk
        FOREIGN KEY (specialist_id)
        REFERENCES specialists(id)
        ON DELETE SET NULL,

    CONSTRAINT audit_log_assignment_fk
        FOREIGN KEY (assignment_id)
        REFERENCES assignments(id)
        ON DELETE SET NULL
);


-- ============================================================
-- 7. ÍNDICES
-- ============================================================

CREATE INDEX idx_cases_annotation_case_id
    ON cases(annotation_case_id);

CREATE INDEX idx_cases_region
    ON cases(region);

CREATE INDEX idx_cases_shared
    ON cases(is_shared);

CREATE INDEX idx_assignments_specialist
    ON assignments(specialist_id);

CREATE INDEX idx_assignments_case
    ON assignments(case_id);

CREATE INDEX idx_assignments_status
    ON assignments(status);

CREATE INDEX idx_annotations_assignment
    ON annotations(assignment_id);

CREATE INDEX idx_bounding_boxes_annotation
    ON bounding_boxes(annotation_id);

CREATE INDEX idx_audit_log_specialist
    ON audit_log(specialist_id);

CREATE INDEX idx_audit_log_assignment
    ON audit_log(assignment_id);


-- ============================================================
-- 8. ACTUALIZACIÓN AUTOMÁTICA DE updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER update_assignments_updated_at
BEFORE UPDATE ON assignments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_annotations_updated_at
BEFORE UPDATE ON annotations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_bounding_boxes_updated_at
BEFORE UPDATE ON bounding_boxes
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- ÍNDICE ÚNICO PARA CÓDIGOS DE ACCESO DE ESPECIALISTAS
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS
specialists_access_code_hash_unique
ON public.specialists(access_code_hash)
WHERE access_code_hash IS NOT NULL;
